### ISSUE TITLE
command line REST rereference

### ISSUE THREAD

**Issue by brennanleo** [sccn/REST#2]
I am trying to implement batch use of REST re-referencing, but am unable to access http://www.neuro.uestc.edu.cn/rest/. I want to run something like:

EEG = pop_REST_reref(EEG, EEG.chanlocs) %default lead field file

Without opening up the GUI. Is there a way to implement this?

**Comment by arnodelorme** [comment]
The program is no longer maintained, but if you fix the problem please let us know.
